structure:  
    readme: README.md  
    summary: SUMMARY.md​
    
redirects:  
    paths:
        '^/home/big-commerce': 
        to: 'https://docs.digitalriver.com/big-commerce/bigcommerce/v/1.0-4/install-the-digital-river-app.md'
        regexp: true
