root: ./

structure:  
    readme: README.md  
    summary: SUMMARY.md​
redirects:
  digital-river-api/order-management/returns-and-refunds-1/disputes-and-chargebacks: digital-river-api/developer-resources/digital-river-api-reference/payment-charges.md
