root: ./

structure:  
    readme: ./README.md  
    summary: ./SUMMARY.md 
    
redirects:
    digital-river-api/order-management/fulfillments: digital-river-api/integration-options/checkouts/handling-digital-river-coordinated-fulfillments.md
