root: ./

structure:  
    readme: README.md  
    summary: SUMMARY.md​
    
redirects:  
        home/big-commerce: https://docs.digitalriver.com/bigcommerce/v/1.0-4/install-the-digital-river-app.md
        big-commerce: https://docs.digitalriver.com/bigcommerce/v/1.0-4/install-the-digital-river-app.md        
