structure:  
    readme: README.md  
    summary: SUMMARY.md​
    
redirects:  
    home/big-commerce: .docs.digitalriver.com/bigcommerce/v/1.0-4/install-the-digital-river-app.md
    big-commerce: .docs.digitalriver.com/bigcommerce/v/1.0-4/install-the-digital-river-app.md
