root: ./digital-river-api/

redirects:
  developer-resources/digitalrivercheckout.js-reference/digitalrivercheckout-object/components/address-component: developer-resources/digitalrivercheckout.js-reference/digitalrivercheckout-object/components/shipping-component.md

structure:  
    readme: README.md  
    summary: SUMMARY.md​

