root: ./digital-river-api/

​structure:
  readme: README.md
  summary: SUMMARY.md​

redirects:
  developer-resources/digital-river-api-reference/subscriptions: digital-river-apis-reference/s8PjaECtf9kQtTXu8xRQ/subscriptions.md
  https://www.digitalriver.com/docs/digital-river-api-reference/#tag/Subscriptions: digital-river-apis-reference/s8PjaECtf9kQtTXu8xRQ/subscriptions.md
  quick-start-guide: administration/dashboard/quick-start-guide
  general-resources/glossary#tariff-code: general-resources/glossary#cross-border.md
