root: ./

redirects:
  digital-river-api/integration-options/low-code-checkouts/using-a-shipping-endpoint: ./digital-river-api/developer-resources/digital-river-api-reference.md

structure:  
    readme: README.md  
    summary: SUMMARY.md​

