structure:  
    readme: README.md  
    summary: SUMMARY.md​
    
redirects:  
    home/big-commerce: .bigcommerce/v/1.0-4/install-the-digital-river-app
    big-commerce: .bigcommerce/v/1.0-4/install-the-digital-river-app
