root: ./

redirects:
  digital-river-api/payments/payment-sources: digital-river-api/payments/payment-sources/using-the-source-identifier.md

structure:  
    readme: README.md  
    summary: SUMMARY.md​

