root: ./

structure:  
    readme: README.md  
    summary: SUMMARY.md​ 
    
redirects:
    digital-river-api/order-management/fulfillments: digital-river-api/integration-options/checkouts/handling-digital-river-coordinated-fulfillments.md
    digital-river-api/order-management/fulfillments#digital-river-coordinated-fulfillments: digital-river-api/integration-options/checkouts/handling-digital-river-coordinated-fulfillments.md
    digital-river-api/order-management/fulfillments#assisted-fulfillment-model: digital-river-api/integration-options/checkouts/handling-digital-river-coordinated-fulfillments#assisted-fulfillment-model.md
    digital-river-api/order-management/fulfillments#automated-fulfillment-model: digital-river-api/integration-options/checkouts/handling-digital-river-coordinated-fulfillments#automated-fulfillment-model.md
