root: ./

redirects:
  developer-resources/digitalrivercheckout.js-reference/digitalrivercheckout-object/components/address-component: developer-resources/digitalrivercheckout.js-reference/digitalrivercheckout-object/components/shipping-component.md

