root: ./home/

redirects:
  digital-river-api/integration-options/low-code-checkouts/using-a-shipping-endpoint: digital-river-api/integration-options/low-code-checkouts.md

structure:  
    readme: README.md  
    summary: SUMMARY.md​

